version: '3.8'

services:
  tgcrosschat:
    build:
      context: .
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TOPICS_CHANNEL_ID=${TOPICS_CHANNEL_ID}
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: tgcrosschat
    volumes:
      - ./mongo_data:/data/db

