version: '3.8'

services:
  tgcrosschat:
    build:
      context: .
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TOPICS_CHANNEL_ID=${TOPICS_CHANNEL_ID}
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    # container_name: mongo
    volumes:
      - ./mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mongo-express:
    image: mongo-express
    # container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=tgcc
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    profiles: ["manual"]
